steps:
  # Step 1: Build the container image using the Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/scanpass:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/scanpass:latest'
      - '.'

  # Step 2: Push the built image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/scanpass:$COMMIT_SHA'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/scanpass:latest'

  # Step 3: Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'scanpass'
      - '--image'
      - 'gcr.io/$PROJECT_ID/scanpass:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'

images:
  - 'gcr.io/$PROJECT_ID/scanpass:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/scanpass:latest'
